# Site settings
name: Will_the_Wizard's Blog
email: sxlvlm@outlook.com
author: Will X.S.
url: https://iwtw666.github.io
resume_site:
github: https://github.com/iwtw666/
baseurl: 
description: You are more than what you have become.
meta_description: Will_the_Wizard's Personal Blog;
motto: Was mich nicht umbringt, macht mich stärker.
banner: Enjoy the Life.

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: iwtw666

# Build settings
markdown: kramdown

baidu_analysis:

